create table if not exists public.kpi_metric (
  id bigint generated by default as identity primary key,
  name text not null,
  kind text not null check (kind in ('quant','qual')),
  unit text,
  target numeric,
  method text,
  created_at timestamptz not null default now()
);
create table if not exists public.kpi_entry (
  id bigint generated by default as identity primary key,
  metric_id bigint references public.kpi_metric(id) on delete set null,
  value numeric not null,
  recorded_on date not null default current_date,
  note text,
  created_at timestamptz not null default now()
);
create table if not exists public.kpi_note (
  id bigint generated by default as identity primary key,
  metric_id bigint references public.kpi_metric(id) on delete set null,
  content text,
  photo_url text,
  recorded_on date not null default current_date,
  created_at timestamptz not null default now()
);
create table if not exists public.rr_department (
  id text primary key,
  name text not null,
  department_type text not null,
  parent_id text references public.rr_department(id) on delete set null,
  manager_name text,
  created_at timestamptz not null default now()
);
create table if not exists public.rr_member (
  id bigint generated by default as identity primary key,
  name text not null unique,
  level text not null,
  skills text[] not null default '{}',
  experience numeric not null default 0,
  task_types text[] not null default '{}',
  capacity_hours numeric not null default 24,
  availability numeric not null default 1 check (availability between .25 and 1),
  max_workload numeric not null default 85,
  workload numeric not null default 0 check (workload between 0 and 150),
  profile_source text not null default 'grade_default',
  department_id text references public.rr_department(id) on delete set null,
  created_at timestamptz not null default now()
);
create table if not exists public.rr_task (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  created_by text not null,
  owner_name text,
  due_on date,
  status text not null default 'unassigned',
  task_type text,
  difficulty text,
  required_level text,
  required_skills text[] not null default '{}',
  min_experience numeric not null default 0,
  estimated_hours numeric not null default 0,
  collaborators text[] not null default '{}',
  assignment_mode text not null default 'single',
  required_assignees integer not null default 1,
  requesting_department_id text references public.rr_department(id) on delete set null,
  target_department_id text references public.rr_department(id) on delete set null,
  created_at timestamptz not null default now(),
  assigned_at timestamptz,
  assignment_hours numeric
);
create table if not exists public.rr_task_assignee (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.rr_task(id) on delete cascade,
  member_name text not null,
  role text not null default 'co_assignee',
  assigned_by text,
  assigned_at timestamptz not null default now(),
  unique (task_id, member_name)
);
create table if not exists public.rr_assignment_history (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.rr_task(id) on delete cascade,
  previous_owners text[] not null default '{}',
  new_owners text[] not null default '{}',
  reason text,
  changed_by text,
  changed_at timestamptz not null default now()
);
create table if not exists public.rr_task_edit_history (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.rr_task(id) on delete cascade,
  changed_fields text[] not null default '{}',
  previous_data jsonb,
  new_data jsonb,
  reason text not null,
  changed_by text,
  changed_at timestamptz not null default now()
);
create table if not exists public.rr_handover (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.rr_task(id) on delete cascade,
  from_member text,
  to_member text,
  current_status text,
  pending_items text,
  next_actions text,
  related_contacts text,
  handover_note text,
  handed_over_at timestamptz,
  confirmed_at timestamptz
);
create table if not exists public.rr_task_satisfaction (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.rr_task(id) on delete cascade,
  owner_name text,
  submitted_by text,
  fit_score numeric check (fit_score between 1 and 5),
  load_score numeric check (load_score between 1 and 5),
  challenge_score numeric check (challenge_score between 1 and 5),
  comment text,
  recorded_on date not null default current_date
);
create table if not exists public.rr_decision_log (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.rr_task(id) on delete cascade,
  reviewer text,
  approver text,
  final_decider text,
  decision text not null,
  decision_note text,
  decided_at timestamptz not null default now()
);
create table if not exists public.rr_task_quality_review (
  id bigint generated by default as identity primary key,
  task_id bigint references public.rr_task(id) on delete cascade,
  issue_type text not null,
  status text not null default 'open',
  detected_on date not null default current_date,
  resolved_on date,
  reviewer text,
  note text
);
create table if not exists public.rr_member_role (
  id bigint generated by default as identity primary key,
  member_name text not null,
  area text not null,
  task_id bigint references public.rr_task(id) on delete cascade
);
create table if not exists public.rr_app_state (
  id text primary key default 'default',
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

create index if not exists rr_task_assignee_task_idx on public.rr_task_assignee(task_id);
create index if not exists rr_task_assignee_member_idx on public.rr_task_assignee(member_name);
create index if not exists rr_task_status_idx on public.rr_task(status);
create index if not exists rr_task_due_idx on public.rr_task(due_on);
create index if not exists rr_quality_issue_idx on public.rr_task_quality_review(issue_type, status);

alter table public.kpi_metric enable row level security;
alter table public.kpi_entry enable row level security;
alter table public.kpi_note enable row level security;
alter table public.rr_department enable row level security;
alter table public.rr_member enable row level security;
alter table public.rr_task enable row level security;
alter table public.rr_task_assignee enable row level security;
alter table public.rr_assignment_history enable row level security;
alter table public.rr_task_edit_history enable row level security;
alter table public.rr_handover enable row level security;
alter table public.rr_task_satisfaction enable row level security;
alter table public.rr_decision_log enable row level security;
alter table public.rr_task_quality_review enable row level security;
alter table public.rr_member_role enable row level security;
alter table public.rr_app_state enable row level security;

do $$ declare t text; begin
  foreach t in array array['kpi_metric','kpi_entry','kpi_note','rr_department','rr_member','rr_task','rr_task_assignee','rr_assignment_history','rr_task_edit_history','rr_handover','rr_task_satisfaction','rr_decision_log','rr_task_quality_review','rr_member_role','rr_app_state'] loop
    execute format('drop policy if exists %I_public_access on public.%I', t, t);
    execute format('create policy %I_public_access on public.%I for all to anon, authenticated using (true) with check (true)', t, t);
  end loop;
end $$;

insert into public.kpi_metric (name, kind, unit, target, method)
select '핵심 업무 R&R 지정률', 'quant', '%', 100, '담당자 지정 업무 / 핵심 업무 * 100'
where not exists (select 1 from public.kpi_metric where name = '핵심 업무 R&R 지정률');
